### ISSUE TITLE
프로젝트 세팅 - scaffolding

### ISSUE THREAD

**Issue by syssys131** [Quizeloper/quizeloper-web-monorepo#1]
```[tasklist]
### Tasks
- [x] tsconfig 설정
- [ ] eslint 설정
- [x] prettier 설정
- [ ] husky, lint-staged 설정
- [ ] 환경 변수 설정
- [ ] next config 설정
- [ ] 내부 패키지 설정
- [ ] 워크스페이스 설정
- [ ] Storybook 설정
- [ ] 컨벤션 설정 (코드 및 파일 네이밍, 커밋 메시지, 이슈 및 브랜치 네이밍 등)
```
